[tool.poetry]
name = "symspellpy"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"
codecov = "^2.0.22"
coverage = "^5.1"
numpy = "^1.18.3"
pytest-cov = "^2.8.1"
jellyfish = "^0.7.2"
pyxdameraulevenshtein = "^1.5.3"
weighted-levenshtein = "^0.2.1"
unidecode = "^1.1.1"
scikit-learn = "^0.22.2"
nltk = "^3.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
